# Generated by Django 5.1.6 on 2025-03-09 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_textentry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Text entries'},
        ),
        migrations.AddField(
            model_name='textentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textentry',
            name='processed_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
